apiVersion: 1

datasources:
  - name: ClickHouse Network Telemetry
    uid: clickhouse-network-telemetry
    type: grafana-clickhouse-datasource
    access: proxy
    isDefault: true
    jsonData:
      host: clickhouse
      port: 9000
      protocol: native
      secure: false
      username: default
      defaultDatabase: network_telemetry
    secureJsonData:
      password: lab

