replicaCount: 2
image:
  repository: network-pj/edge-agent
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

resources: {}

nodeSelector: {}

tolerations: []

api:
  repository: network-pj/backend-api
  tag: latest


*** End Patch
